(function(){
'use strict';
const $=id=>document.getElementById(id);
const cfg=window.CASHTOP_FIREBASE?.config||{};
const base=String(cfg.databaseURL||'').replace(/\/+$/,'');
const adminRoot=String(window.CASHTOP_FIREBASE?.adminRootPath||'cashTopExchange/cashTopAdmin').replace(/^\/+|\/+$/g,'');
const companyRoot=String(window.CASHTOP_FIREBASE?.rootPath||'cashTopExchange/cashTopPOS').replace(/^\/+|\/+$/g,'');
const LOCAL_KEY='cashtop_admin_index_v14';
const LEGACY_LOCAL_KEY='cashtop_admin_index_v13';
const SESSION_KEY='cashtop_superadmin_session';
let state={superAdmin:null,companies:{},keyIndex:{},updatedAt:0};
let editingKey='';
const parse=(v,f)=>{try{return JSON.parse(v)??f}catch(_){return f}};
const rawGet=k=>Storage.prototype.getItem.call(localStorage,k);
const rawSet=(k,v)=>Storage.prototype.setItem.call(localStorage,k,String(v));
const normalizeKey=v=>String(v||'').trim().toUpperCase();
const safeSeg=v=>String(v||'').trim().replace(/[.#$\[\]\/]/g,'_');
function status(message,type='info'){const box=$('authStatus');if(!box)return;box.className=`status show ${type}`;box.textContent=message}
function toast(message,type='success'){
 let host=document.getElementById('adminToastHost');if(!host){host=document.createElement('div');host.id='adminToastHost';host.style.cssText='position:fixed;bottom:18px;right:18px;z-index:9999;display:grid;gap:8px;max-width:min(380px,calc(100vw - 36px))';document.body.appendChild(host)}
 const el=document.createElement('div');el.textContent=message;el.style.cssText=`padding:11px 14px;border-radius:8px;color:#fff;font:700 11px Cairo;box-shadow:0 8px 25px rgba(0,0,0,.18);background:${type==='error'?'#dd4b39':type==='warning'?'#f39c12':'#00a65a'}`;host.appendChild(el);setTimeout(()=>el.remove(),3600)
}
async function hashPassword(password,salt){const data=new TextEncoder().encode(`${salt}:${password}`);const digest=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function makeSalt(){return crypto.randomUUID?crypto.randomUUID():`${Date.now()}_${Math.random()}`}
let adminDatabaseToken='';
async function getAdminDatabaseToken(){if(adminDatabaseToken)return adminDatabaseToken;if(!cfg.apiKey)return '';const response=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${encodeURIComponent(cfg.apiKey)}`,{method:'POST',headers:{'Content-Type':'application/json;charset=UTF-8'},body:JSON.stringify({returnSecureToken:true}),cache:'no-store'});if(!response.ok)return '';const data=await response.json().catch(()=>({}));adminDatabaseToken=data.idToken||'';return adminDatabaseToken}
function authUrl(url,token){return token?`${url}${url.includes('?')?'&':'?'}auth=${encodeURIComponent(token)}`:url}
async function request(url,options={},timeout=18000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{let response=await fetch(url,{...options,signal:controller.signal,cache:'no-store'});if(!response.ok&&(response.status===401||response.status===403)){const token=await getAdminDatabaseToken().catch(()=>'');if(token)response=await fetch(authUrl(url,token),{...options,signal:controller.signal,cache:'no-store'})}if(!response.ok){const p=await response.json().catch(()=>null);throw new Error(String(p?.error?.message||p?.error||`Firebase ${response.status}`))}return response}finally{clearTimeout(timer)}}
function adminUrl(path=''){return `${base}/${adminRoot}${path?'/'+path:''}.json`}
function companyUrl(companyId){return `${base}/${companyRoot}/${safeSeg(companyId)}.json`}
async function loadRemote(){if(!base||!navigator.onLine)return null;try{const r=await request(adminUrl());return await r.json()}catch(e){console.warn('[ADMIN] load remote',e);return null}}
function loadLocal(){return parse(rawGet(LOCAL_KEY),null)||parse(rawGet(LEGACY_LOCAL_KEY),null)}
function normalizeState(value){const s=value&&typeof value==='object'?value:{};const companies=s.companies&&typeof s.companies==='object'?s.companies:{};Object.values(companies).forEach(c=>{c.backupImportEnabled=c.backupImportEnabled===true});return {superAdmin:s.superAdmin||null,companies,keyIndex:s.keyIndex&&typeof s.keyIndex==='object'?s.keyIndex:{},updatedAt:Number(s.updatedAt||0)}}
async function saveState(){state.updatedAt=Date.now();rawSet(LOCAL_KEY,JSON.stringify(state));if(base&&navigator.onLine){try{await request(adminUrl(),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});$('syncMode').textContent='Firebase متزامن + تخزين محلي'}catch(e){$('syncMode').textContent='محلي — تعذر Firebase';toast(`حُفظ محلياً، وتعذرت مزامنة الإدارة: ${e.message}`,'warning')}}}
function sessionValid(){const s=parse(rawGet(SESSION_KEY),null);return Boolean(s&&s.expiresAt>Date.now())}
function showApp(){$('authView').classList.add('hidden');$('appView').classList.remove('hidden');render()}
function setupAuthView(){const first=!state.superAdmin;$('confirmField').classList.toggle('hidden',!first);$('authSubtitle').textContent=first?'إنشاء أول حساب للمشرف العام':'دخول المشرف العام';$('authButton').innerHTML=first?'<i class="fa-solid fa-user-shield"></i> إنشاء حساب الإدارة':'<i class="fa-solid fa-shield-halved"></i> دخول الإدارة'}
async function handleAuth(e){e.preventDefault();const username=$('superUsername').value.trim(),password=$('superPassword').value;if(!state.superAdmin){const confirm=$('superPasswordConfirm').value;if(password!==confirm)return status('كلمتا المرور غير متطابقتين.','error');if(password.length<6)return status('كلمة المرور يجب أن تكون 6 أحرف على الأقل.','error');const salt=makeSalt();state.superAdmin={username,passwordHash:await hashPassword(password,salt),salt,createdAt:new Date().toISOString(),authVersion:Date.now()};await saveState();rawSet(SESSION_KEY,JSON.stringify({username,expiresAt:Date.now()+8*60*60*1000}));showApp();return}const expected=await hashPassword(password,state.superAdmin.salt);if(String(username).toLowerCase()!==String(state.superAdmin.username).toLowerCase()||expected!==state.superAdmin.passwordHash)return status('بيانات المشرف العام غير صحيحة.','error');rawSet(SESSION_KEY,JSON.stringify({username:state.superAdmin.username,expiresAt:Date.now()+8*60*60*1000}));showApp()}
function planNote(){const plan=$('plan').value;$('planDetails').innerHTML=plan==='plus'?'<b>Plus:</b> تطبق حدود الخطة المحددة على الشركة.':'<b>Pro:</b> جميع الحدود غير محدودة.'}
function calcExpiry(start=new Date()){const unit=$('durationUnit').value,q=Math.max(1,Number($('durationQuantity').value||1));if(unit==='unlimited')return '';const d=new Date(start);if(unit==='minute')d.setMinutes(d.getMinutes()+q);if(unit==='hour')d.setHours(d.getHours()+q);if(unit==='day')d.setDate(d.getDate()+q);if(unit==='month')d.setMonth(d.getMonth()+q);if(unit==='year')d.setFullYear(d.getFullYear()+q);return d.toISOString()}
function updateExpiryPreview(){const unit=$('durationUnit').value;$('durationQuantity').disabled=unit==='unlimited';const end=calcExpiry();$('expiryPreview').textContent=end?'تم تحديد مدة الاشتراك.':'مدة الاشتراك غير محدودة.'}
function generateKey(){return `CT-${Math.random().toString(36).slice(2,6).toUpperCase()}-${Date.now().toString(36).slice(-5).toUpperCase()}`}
function companyAccess(company){return {companyId:company.companyId,companyKey:company.key,companyName:company.companyName,status:company.status,plan:company.plan,startAt:company.startAt,endAt:company.endAt,durationUnit:company.durationUnit,durationQuantity:company.durationQuantity,backupImportEnabled:company.backupImportEnabled===true,authVersion:company.authVersion,updatedAt:Date.now(),manager:{id:`ADMIN_${company.companyId}`,username:company.managerUsername,password:company.managerPassword,displayName:'مدير الشركة',role:'admin',active:company.status==='active',permissions:{},authVersion:company.authVersion}}}
function payload(value){return {value:JSON.stringify(value),valueEncoding:'local-storage-json-v1',deleted:false,updatedAt:Date.now(),revision:1,deviceId:'admin-console',page:'admin.html'}}
async function writeCompany(company){let node={};if(base&&navigator.onLine){try{const r=await request(companyUrl(company.companyId));node=await r.json()||{}}catch(_){node={}}}node={...node,datasets:{...(node.datasets||{}),cashtop_company_access:payload(companyAccess(company))},meta:{...(node.meta||{}),companyId:company.companyId,companyKey:company.key,companyName:company.companyName,schema:14,updatedAt:Date.now(),managedBy:'cashTopAdmin'}};if(base&&navigator.onLine)await request(companyUrl(company.companyId),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(node)});const licenses=parse(rawGet('cashtop_admin_licenses'),'[]')||[];const li=licenses.findIndex(x=>x.companyId===company.companyId);const license={id:company.companyId,key:company.key,companyId:company.companyId,companyName:company.companyName,status:company.status,plan:company.plan,startAt:company.startAt,endAt:company.endAt,durationUnit:company.durationUnit,durationQuantity:company.durationQuantity,backupImportEnabled:company.backupImportEnabled===true};if(li>=0)licenses[li]=license;else licenses.push(license);rawSet('cashtop_admin_licenses',JSON.stringify(licenses));const users=parse(rawGet('cashtop_admin_users'),'[]')||[];const ui=users.findIndex(x=>x.companyId===company.companyId&&x.role==='admin');const user={id:`ADMIN_${company.companyId}`,companyKey:company.key,companyId:company.companyId,username:company.managerUsername,password:company.managerPassword,displayName:'مدير الشركة',role:'admin',active:company.status==='active'};if(ui>=0)users[ui]=user;else users.push(user);rawSet('cashtop_admin_users',JSON.stringify(users))}
async function saveCompany(e){e.preventDefault();const key=normalizeKey($('companyKey').value);if(!key)return toast('أدخل مفتاح الشركة.','error');const existingId=editingKey&&state.keyIndex[safeSeg(editingKey)]?.companyId;const duplicate=state.keyIndex[safeSeg(key)]?.companyId;if(duplicate&&duplicate!==existingId)return toast('مفتاح الشركة مستخدم لشركة أخرى.','error');const existing=existingId?state.companies[existingId]:null;const now=new Date();const company={companyId:existing?.companyId||`CMP_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,companyName:$('companyName').value.trim(),key,managerUsername:$('managerUsername').value.trim(),managerPassword:$('managerPassword').value||existing?.managerPassword||'',plan:$('plan').value,status:$('status').value,backupImportEnabled:$('backupImportEnabled').value==='true',durationUnit:$('durationUnit').value,durationQuantity:$('durationUnit').value==='unlimited'?null:Math.max(1,Number($('durationQuantity').value||1)),startAt:existing?.startAt||now.toISOString(),endAt:calcExpiry(existing?.startAt?new Date(existing.startAt):now),authVersion:Date.now(),createdAt:existing?.createdAt||now.toISOString(),updatedAt:now.toISOString()};if(!company.companyName||!company.managerUsername||!company.managerPassword)return toast('أكمل اسم الشركة وبيانات مديرها.','error');if(editingKey&&normalizeKey(editingKey)!==key)delete state.keyIndex[safeSeg(editingKey)];state.companies[company.companyId]=company;state.keyIndex[safeSeg(key)]={companyId:company.companyId,key,updatedAt:Date.now()};try{await writeCompany(company);await saveState();toast('تم حفظ الشركة والمفتاح ومزامنتهما.');resetForm();render()}catch(err){toast(err.message||'تعذر حفظ الشركة.','error')}}
function resetForm(){editingKey='';$('editingKey').value='';$('formTitle').textContent='إنشاء شركة ومفتاح جديد';$('companyForm').reset();$('companyKey').value=generateKey();$('durationUnit').value='month';$('durationQuantity').value=1;$('plan').value='plus';$('status').value='active';$('backupImportEnabled').value='false';$('cancelEdit').classList.add('hidden');planNote();updateExpiryPreview()}
function editCompany(id){const c=state.companies[id];if(!c)return;editingKey=c.key;$('editingKey').value=c.key;$('formTitle').textContent=`تعديل ${c.companyName}`;$('companyName').value=c.companyName;$('companyKey').value=c.key;$('managerUsername').value=c.managerUsername;$('managerPassword').value=c.managerPassword;$('plan').value=c.plan;$('status').value=c.status;$('backupImportEnabled').value=String(c.backupImportEnabled===true);$('durationUnit').value=c.durationUnit||'unlimited';$('durationQuantity').value=c.durationQuantity||1;$('cancelEdit').classList.remove('hidden');planNote();updateExpiryPreview();scrollTo({top:0,behavior:'smooth'})}
async function toggleCompany(id){const c=state.companies[id];if(!c)return;c.status=c.status==='active'?'stopped':'active';c.authVersion=Date.now();c.updatedAt=new Date().toISOString();await writeCompany(c);await saveState();render();toast(c.status==='active'?'تم تفعيل المفتاح.':'تم إيقاف المفتاح وستُغلق الجلسات المفتوحة.','warning')}
async function deleteCompany(id){const c=state.companies[id];if(!c||!confirm(`حذف شركة ${c.companyName} وتعطيل مفتاحها؟`))return;c.status='deleted';c.deleted=true;c.authVersion=Date.now();delete state.keyIndex[safeSeg(c.key)];await writeCompany(c);await saveState();render();toast('تم تعطيل الشركة وحذف المفتاح من فهرس الدخول.','warning')}
async function copyKey(key){try{await navigator.clipboard.writeText(key)}catch(_){const input=document.createElement('input');input.value=key;document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}toast('تم نسخ المفتاح.')}
function fmt(v){return v?new Date(v).toLocaleString('ar-EG'):'غير محدود'}
function render(){const list=Object.values(state.companies||{}).filter(c=>!c.deleted);$('statAll').textContent=list.length;$('statActive').textContent=list.filter(c=>c.status==='active'&&(!c.endAt||new Date(c.endAt)>new Date())).length;$('statPlus').textContent=list.filter(c=>c.plan==='plus').length;$('statPro').textContent=list.filter(c=>c.plan==='pro').length;$('companiesBody').innerHTML=list.length?list.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).map(c=>{const expired=c.endAt&&Date.now()>=new Date(c.endAt).getTime(),statusClass=expired?'expired':c.status==='active'?'active':'stopped',statusText=expired?'منتهي':c.status==='active'?'نشط':'موقوف',lock=c.backupImportEnabled===true?'<span class="badge active"><i class="fa-solid fa-lock-open"></i> مفتوح</span>':'<span class="badge stopped"><i class="fa-solid fa-lock"></i> مقفل</span>';return `<tr><td data-label="الشركة"><b>${escapeHtml(c.companyName)}</b></td><td data-label="المفتاح"><div class="key-cell"><code>${escapeHtml(c.key)}</code><button class="btn btn-light" type="button" title="نسخ المفتاح" onclick="AdminPage.copy(decodeURIComponent('${encodeURIComponent(c.key)}'))"><i class="fa-solid fa-copy"></i></button></div></td><td data-label="الخطة"><span class="badge ${c.plan}">${c.plan==='plus'?'Plus':'Pro'}</span></td><td data-label="الحالة"><span class="badge ${statusClass}">${statusText}</span></td><td data-label="المدير">${escapeHtml(c.managerUsername)}</td><td data-label="استيراد النسخ">${lock}</td><td data-label="البدء">${fmt(c.startAt)}</td><td data-label="الانتهاء">${fmt(c.endAt)}</td><td data-label="الإجراءات"><div class="actions"><button class="btn btn-light" onclick="AdminPage.edit('${c.companyId}')"><i class="fa-solid fa-pen"></i></button><button class="btn ${c.status==='active'?'btn-warning':'btn-success'}" onclick="AdminPage.toggle('${c.companyId}')"><i class="fa-solid fa-power-off"></i></button><button class="btn btn-danger" onclick="AdminPage.remove('${c.companyId}')"><i class="fa-solid fa-trash"></i></button></div></td></tr>`}).join(''):'<tr><td colspan="9" style="padding:25px;color:#64748b">لا توجد شركات بعد.</td></tr>'}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.AdminPage={edit:editCompany,toggle:toggleCompany,remove:deleteCompany,copy:copyKey};
window.addEventListener('DOMContentLoaded',async()=>{state=normalizeState(await loadRemote()||loadLocal());rawSet(LOCAL_KEY,JSON.stringify(state));setupAuthView();if(sessionValid())showApp();$('authForm').addEventListener('submit',handleAuth);$('companyForm').addEventListener('submit',saveCompany);$('generateKey').addEventListener('click',()=>{$('companyKey').value=generateKey()});$('plan').addEventListener('change',planNote);$('durationUnit').addEventListener('change',updateExpiryPreview);$('durationQuantity').addEventListener('input',updateExpiryPreview);$('cancelEdit').addEventListener('click',resetForm);$('logoutBtn').addEventListener('click',()=>{localStorage.removeItem(SESSION_KEY);location.reload()});resetForm()});
})();
